### ISSUE TITLE
Sorry, but why does Windows release files using elf

### ISSUE THREAD

**Issue by AdminHcat** [xeonds/phi-rank-query#1]
![image](https://github.com/user-attachments/assets/dc88f87f-2947-4086-922e-ec668f24b6cb)

**Comment by xeonds** [comment]
That's unreasonable. According to the `build command` in Makefile, the target is windows-amd64, but it seems the cross compile process on my linux failed to generate correct windows version.

I assume the reason might be related to `cgo_enabled` or something else.

Anyway, **the correct version is in release now**, or you can **compile from src on your windows pc**.

And you can try to commit to the `main branch's Makefile` to fix the cross compile error.
